version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial_management_app_prod
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - financial_management_network
    depends_on:
      - db
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

  web:
    image: nginx:alpine
    container_name: financial_management_web_prod
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - financial_management_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: financial_management_db_prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: financial_management
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    volumes:
      - dbdata_prod:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - financial_management_network

networks:
  financial_management_network:
    driver: bridge

volumes:
  dbdata_prod:
    driver: local 