version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial_management_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - financial_management_network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: financial_management_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - financial_management_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: financial_management_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: financial_management
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: password
      MYSQL_USER: financial_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - financial_management_network

networks:
  financial_management_network:
    driver: bridge

volumes:
  dbdata:
    driver: local 